--- 
- name: install tomcat9 using ansible
  hosts: demo
  become: true
  tasks:
          - name: update the system packages
            package:
                    upgrade: yes
                    update_cache: yes
          - name: create a tomcat group
            user:
                    name: tomcat
          - name: create a tomcat user
            group:
                    name: tomcat
          - name: install java
            package:
                    name: default-jdk
                    state: present
          - name: Create a Tomcat Directory
            file:
               path: /opt/tomcat
               owner: tomcat
               group: tomcat
               mode: 755
               recurse: yes          
          - name: download the tomcat9 package
            get_url:
                    url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.65/bin/apache-tomcat-9.0.65.tar.gz
                    dest: /opt/tomcat
          
          - name: extract the tomcat package
            unarchive:
                    src: /opt/tomcat/apache-tomcat-9.0.65.tar.gz
                    dest: /opt/tomcat
                    remote_src: yes
                    extra_opts: [--strip-components=1]
          - name: Change ownership of tomcat directory
            file:
             path: /opt/tomcat
             owner: tomcat
             group: tomcat
             mode: "u+rwx,g+rx,o=rx"
             recurse: yes 
             state: directory
          - name: Copy Tomcat service from local to remote
            copy:
              src: /etc/tomcat.service
              dest: /etc/systemd/system/
              mode: 0755

          - name: Start and Enable Tomcat 9  on sever
            systemd:
              name: tomcat
              state: started
              daemon_reload: true
