--- 
- name: install tomcat7 using ansible
  hosts: demo
  become: true
  tasks:
          - name: update the system packages
            package:
                    upgrade: yes
                    update_cache: yes
          - name: create a tomcat group
            user:
                    name: tomcat
          - name: create a tomcat user
            group:
                    name: tomcat
          - name: install java
            package:
                    name: default-jdk
                    state: present
          - name: Create a Tomcat Directory
            file:
               path: /opt/tomcat7
               owner: tomcat
               group: tomcat
               mode: 755
               recurse: yes          
          - name: download the tomcat7 package
            get_url:
                    url: https://archive.apache.org/dist/tomcat/tomcat-7/v7.0.32/bin/apache-tomcat-7.0.32-fulldocs.tar.gz
                    dest: /opt/tomcat7
          
          - name: extract the tomcat package
            unarchive:
                    src: /opt/tomcat7/apache-tomcat-7.0.32-fulldocs.tar.gz
                    dest: /opt/tomcat7
                    remote_src: yes
          - name: start tomcat services
            shell: nohup /opt/tomcat7/apache-tomcat-7.0.90/bin/startup.sh
