--- #tomcat deployment
- name: deploy the artifact
  hosts: all
  become: true
  tasks:
          - name: stop the tomcat
            service:
                    name: tomcat
                    state: stopped
                    daemon_reload: true
          - name: backup the war directory
            archive:
                    path: /opt/tomcat/webapps
                    dest: /opt/tomcat/webapps.tar.gz
                    format: gz
                    remove: yes
          - name: copy the war
            copy:
              src: /var/lib/jenkins/workspace/rahul_tomcat7_build/target/java-hello-world.war
              dest: /opt/tomcat/webapps

          - name: restart the tomcat
            service:
                    name: tomcat
                    state: restarted
          - name: health check
            command: curl -s -o /dev/null -w "%{http_code}" http://192.168.57.8:8080/java-hello-world/

          - name: health check module
            uri:
              url: "http://192.168.57.8:8080/java-hello-world/"
            register: result
            delay: 10
            failed_when: result.status != 200       
